file = open('output.txt','w')
file.write('Hello Python!')
file.close()
file1 = open('output.txt','r')
abc = file1.read()
print(abc)
file1.close()
file2 = open('output.txt','a')
file2.write('\nLearning file handling in python')
file2.close()
file3 = open('output.txt','r')
abc1 = file3.read()
print(abc1)
file3.close()